# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      DBPASS: example
      DBHOST: db
      DBUSER: root
      DB: ccMM
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./mysqldump:/docker-entrypoint-initdb.d

  node:
    container_name: topsection-server
    restart: always
    build: .
    ports:
      - '8888:8888'
    depends_on: 
      - db
    environment:
      PORT: 8888
      DBPASS: example
      DBHOST: db
      DBUSER: root
      DB: ccMM

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080